# Copyright (c) 2020 Huawei Technologies Co., Ltd.
# Licensed under CC BY-NC-SA 4.0 (Attribution-NonCommercial-ShareAlike 4.0 International) (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode
#
# The code is released for academic research use only. For commercial use, please contact Huawei Technologies Co., Ltd.
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# This file contains content licensed by https://github.com/xinntao/BasicSR/blob/master/LICENSE/LICENSE

#### general settings
name: train
use_tb_logger: true
model: SRFlow
distortion: sr
scale: 4
gpu_ids: [ 0 ]

#### datasets
datasets:
  train:
    name: CelebA_160_tr
    mode: LRHR_PKL
    dataroot_GT: /seushare2/home/yuanpeng/Desktop/NTIRE2021/pkls/train.pklv4
    dataroot_LQ: /seushare2/home/yuanpeng/Desktop/NTIRE2021/pkls/train_X4.pklv4
    quant: 32

    use_shuffle: true
    n_workers: 3  # per GPU
    batch_size: 32
    GT_size: 256
    use_flip: true
    color: RGB
  val:
    name: CelebA_160_va
    mode: LRHR_PKL
    dataroot_GT: /seushare2/home/yuanpeng/Desktop/NTIRE2021/pkls/DIV2K-va_HR.pklv4
    dataroot_LQ: /seushare2/home/yuanpeng/Desktop/NTIRE2021/pkls/DIV2K-va_HR_X4.pklv4
    quant: 32
    n_max: 20

#### Test Settings
#dataroot_GT: /seushare2/home/yuanpeng/Desktop/NTIRE2021/DIV2K-va_HR
#dataroot_LR: /seushare2/home/yuanpeng/Desktop/NTIRE2021/DIV2K-va_LR
dataroot_LR: ../DIV2K-te_4X
model_path: ../trained_models/x4/80000_G.pth
heat: 0.9 # This is the standard deviation of the latent vectors

n_outputs: 10

#### network structures
network_G:
  which_model_G: SRFlowNet
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 23
  upscale: 4
  train_RRDB: false
  train_RRDB_delay: 0.5

  flow:
    K: 16
    L: 3
    noInitialInj: true
    coupling: CondAffineSeparatedAndCond
    additionalFlowNoAffine: 2
    split:
      enable: true
    fea_up0: true
    stackRRDB:
      blocks: [ 1, 8, 15, 22 ]
      concat: true

#### path
path:
#  pretrain_model_G: /seu_share/home/yuanpeng/olddata/yuanpeng/Desktop/NTIRE2021/SRFlowX4/experiments/train/models/62400_G.pth
  strict_load: true
  resume_state: auto

#### training settings: learning rate scheme, loss
train:
  manual_seed: 10
  lr_G: !!float 2.5e-4
  weight_decay_G: 0
  beta1: 0.9
  beta2: 0.99
  lr_scheme: MultiStepLR
  warmup_iter: -1  # no warm up
  lr_steps_rel: [ 0.5, 0.75, 0.9, 0.95 ]
  lr_gamma: 0.5

  niter: 200000
  val_freq: 40000

#### validation settings
val:
  heats: [ 0.0, 0.5, 0.75, 1.0 ]
  n_sample: 3

#### logger
logger:
  print_freq: 100
#  save_checkpoint_freq: !!float 1e3
  save_checkpoint_freq: 800
